FROM openjdk:8
ADD target/simple-spring-boot-with-docker-0.0.1-SNAPSHOT.jar simple-spring-boot-with-docker-0.0.1-SNAPSHOT.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","simple-spring-boot-with-docker-0.0.1-SNAPSHOT.jar"]